# -*- coding: utf-8 -*-
"""Data_Extracction_for_Small_AOI_from_Downloaded_S2_files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l0wl4kI6fDgVDsMZTkjGWVAXVIev6TAJ
"""

# ============================================
# STEP 1: Install Required Libraries (Colab)
# ============================================
!pip install geopandas rasterio openpyxl

# ============================================
# STEP 2: Mount Google Drive
# ============================================
from google.colab import drive
drive.mount('/content/drive')

# ============================================
# STEP 3: Import Libraries
# ============================================
import os
import rasterio
from rasterio.mask import mask
import geopandas as gpd
import pandas as pd
import numpy as np
from datetime import datetime

# ============================================
# STEP 4: Define User Inputs
# ============================================
input_folder = '/content/drive/MyDrive/NAGPUR_HARMONIZED_EVI/'  # Folder with original EVI TIFFs...Same process for..LSWI,NDVI
output_folder = os.path.join(input_folder, 'NAGPUR_HARMONIZED_EVI_clipped_AOIs/')
os.makedirs(output_folder, exist_ok=True)

aoi_path = '/content/drive/MyDrive/NRSC_INTERNSHIP_DATA/Sentinel_2_Nagpur/NAGPUR_AOI/NAGPUR_AOI.shp'  # Nagpur AOI shapefile
output_excel_path = os.path.join(input_folder, 'NAGPUR_HARMONIZED_EVI_summary.xlsx')

# ============================================
# STEP 5: Load AOI Geometry
# ============================================
aoi = gpd.read_file(aoi_path)
aoi_geom = [feature["geometry"] for feature in aoi.__geo_interface__["features"]]

# ============================================
# STEP 6: Initialize Summary List
# ============================================
summary = []

# ============================================
# STEP 7: Loop Through All TIFF Files
# ============================================
for filename in os.listdir(input_folder):
    if filename.endswith('.tif'):
        file_path = os.path.join(input_folder, filename)

        try:
            with rasterio.open(file_path) as src:
                # Clip raster using AOI
                clipped_image, clipped_transform = mask(src, aoi_geom, crop=True)
                clipped_data = clipped_image[0]  # Assuming single band

                # Remove no-data values
                valid_data = clipped_data[clipped_data != src.nodata]

                # Calculate stats
                if valid_data.size > 0:
                    mean_val = float(np.mean(valid_data))
                    min_val = float(np.min(valid_data))
                    max_val = float(np.max(valid_data))
                else:
                    mean_val, min_val, max_val = None, None, None

                # Save clipped raster
                clipped_meta = src.meta.copy()
                clipped_meta.update({
                    "height": clipped_data.shape[0],
                    "width": clipped_data.shape[1],
                    "transform": clipped_transform
                })

                output_tif_path = os.path.join(output_folder, f'clipped_{filename}')
                with rasterio.open(output_tif_path, 'w', **clipped_meta) as dst:
                    dst.write(clipped_image)

                # Extract date from filename (if present)
                try:
                    date_str = ''.join(filter(str.isdigit, filename))
                    date = datetime.strptime(date_str[:8], '%Y%m%d').date()
                except:
                    date = None

                # Append to summary
                summary.append({
                    'FileName': filename,
                    'Date': date,
                    'Mean_EVI': mean_val,
                    'Min_EVI': min_val,
                    'Max_EVI': max_val,
                    'Clipped_File': output_tif_path
                })

                print(f"✅ Processed {filename} → Mean: {mean_val}, Min: {min_val}, Max: {max_val}")

        except Exception as e:
            print(f"❌ Failed to process {filename}: {e}")

# ============================================
# STEP 8: Save Summary to Excel
# ============================================
df = pd.DataFrame(summary)
df.to_excel(output_excel_path, index=False)

print("\n✅ All done!")
print("📝 Excel summary saved to:", output_excel_path)